#!/usr/bin/env bash

SCRIPT_CWD=$(dirname "$(realpath "$0")")
VULKAN_GLSL_COMPILER="glslc"
VULKAN_SDK="$HOME/VulkanSDK/1.4.309.0"
GLSLC_PATH="$VULKAN_SDK/macOS/bin/$VULKAN_GLSL_COMPILER"

SHADER_NAME="triangle"

$GLSLC_PATH $SCRIPT_CWD/$SHADER_NAME.vert -o $SCRIPT_CWD/$SHADER_NAME.vert.spv
$GLSLC_PATH $SCRIPT_CWD/$SHADER_NAME.frag -o $SCRIPT_CWD/$SHADER_NAME.frag.spv

